% Megan Baker, Sarah Ginck, Dennis Ephraim --> Team 24
function [] = disclaimer()
    disp(['DISCLAIMER: for the two matrices you will generate, certain analysis can only' ... 
    ' be computed if the matrices share the same dimenions, or overlap in one dimension ' ... 
    '(ex: one has the same number of columns as the other has rows ']) 
end 